### ISSUE TITLE
Xiaomi Mijia motion sensor

### ISSUE THREAD

**Issue by Gitarcitano** [byjaps/xiaomi_aqara#1]
Does that also work with Xiaomi mijia motion sensor?

I've tried using with zigbee2mqtt, but I didn't notice any difference, even after restarting HA and RPI. Should I do some change in the configuration of this custom_component or zigbee2mqtt?

**Comment by byjaps** [comment]
Yes, it works with mijia and aqara motion sensors paired with Xiaomi's gateway. 
 Just copy everything to the custom_component folder and restart HA.
With this change, the sensors will detect movement, staying "on" for 12 seconds and after another 50 seconds, it will detect movement again. 
With the original component it takes approximately 2 minutes and 30 seconds between detections.
